### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by simax** [binaryage/cljs-devtools-sample#2]
I seem to be unable to build the project. After cloning the repo I get the following error when running `lein cljsbuild auto`  

Error:
`Caused by: clojure.lang.ExceptionInfo: No such namespace: devtools.debug, could not locate devtools/debug.cljs, devtools/debug.cljc, or Closure namespace "devtools.debug"`

**Comment by darwin** [comment]
I was using checkouts directory pointing directly to cljs-devtools. It looks like released jar does not contain same structure (src-debug folder)
