### ISSUE TITLE
'ring' is not a task. See 'lein help'.

### ISSUE THREAD

**Issue by fricze** [binaryage/cljs-devtools-sample#3]
After cloning repo and running `lein demo` I get `'ring' is not a task. See 'lein help'`
It looks like this error should be here, since there's no Ring handler in project.clj, but `lein demo` tries to run `lein do ring server`.
How is `lein demo` supposed to work without Ring configured?

**Comment by darwin** [comment]
I'm sorry. I broke it yesterday when rushing Dirac release.

Please note that server runs on new port. Not 3000 but 7000.

**Comment by fricze** [comment]
It's clear now. Thank you so much!
